site_name: FiveR - Hulpdiensten Nederland
site_url: 'https://stijn-gamettwee.github.io/fivernl/'
site_description: 'Hier vind je van alles over FiveR. Zoals het APV, Wetboek, Commands, Donatie & veel meer..'
site_author: 'stijn_gamet'

copyright: Copyright &copy; 2023 FiveR - Hulpdiensten Nederland | stijn_gamet

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  language: nl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - toc.follow
  favicon: img/fiver-icon.png
  #logo: img/fiver-icon.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: nl
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
# - Wetboek: wetboek.md
  - Commands: commands.md
